using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PhysicalProperties : MonoBehaviour
{
    [SerializeField] float flashPoint; // Flash Point: Temperature required to ignite using external source
    public float temperature = 0;
    public float freezingPoint;
    public bool isIgnited = false;
    public bool isFrozen = false;
    public float pressureGenerationRate = 2f;
    Material material;
    Color defaultColor;
    SphereCollider sphereCollider;
    [SerializeField] float heatResistance; // Resistance to EXTERNAL HEAT sources
    public Vector3 tempChangeDirection;
    public float manaResistance; // Resistance to mana flow
    // To adhere to the magic system, the higher the mana resistance, the more internal heat is generated by a mana current.
    public float manaCharge;
    [SerializeField] GameObject emberSmokePrefab;
    GameObject emberSmokeObject;
    [HideInInspector] public FrozenCluster frozenCluster;
    float frozenClusterSearchRadius = 0.5f;
    bool isManaFizzling = false;
    bool isGlowing = false;

    void Start()
    {
        if (GetComponent<Renderer>())
        {
            material = GetComponent<Renderer>().material;
            defaultColor = material.GetColor("_Color");
        }
        sphereCollider = GetComponent<SphereCollider>();
    }

    void Update()
    {
        if (manaCharge <= 0 && !isManaFizzling)
        {
            BeginManaFizzle();
        }
        if (isManaFizzling && temperature > freezingPoint)
        {
            temperature = freezingPoint;
        }
        if (temperature <= freezingPoint && !isFrozen)
        {
            Freeze();
        }
        if (isIgnited && temperature < flashPoint)
        {
            temperature = flashPoint;
        }
        if (temperature < 6 && temperature > 0 && isGlowing)
        {
            StopGlowing();
        }
        if (temperature > 6 * flashPoint / 7 && temperature < flashPoint && !isGlowing)
        {
            Glow();
        }
        if (temperature >= flashPoint && !isIgnited)
        {
            Ignite();
        }
    }

    void BeginManaFizzle()
    {
        // Use the new shader to fizzle away
        isManaFizzling = true;
        StartCoroutine("ManaFizzle");
        // Instantiate some mana vapour around the object or something
    }

    IEnumerator ManaFizzle()
    {
        float manaFizzleDuration = 1;
        float manaFizzleStrength;
        float elapsedTime = 0;

        while ( elapsedTime < manaFizzleDuration )
        {
            elapsedTime += Time.deltaTime;

            manaFizzleStrength = Mathf.Lerp(-0.01f, 1.5f, elapsedTime / manaFizzleDuration);

            if (material) material.SetFloat("_ManaDrainStrength", manaFizzleStrength);

            yield return null;
        }


        Destroy(gameObject);
    }

    void Freeze()
    {
        if (isManaFizzling) return;
        isFrozen = true;

        List<FrozenCluster> nearbyClusters = FindNearbyFrozenClusters();
        FrozenCluster targetCluster;

        if (nearbyClusters.Count == 0)
        {
            targetCluster = CreateFrozenCluster();
        }
        else
        {
            targetCluster = nearbyClusters[0];

            for (int i = 1; i < nearbyClusters.Count; i++)
            {
                targetCluster.MergeWith(nearbyClusters[i]);
            }
        }

        targetCluster.AddMember(this);
    }

    List<FrozenCluster> FindNearbyFrozenClusters()
    {
        List<FrozenCluster> nearbyClusters = new List<FrozenCluster>();
        Collider[] nearbyColliders = Physics.OverlapSphere(transform.position, frozenClusterSearchRadius);

        for (int i = 0; i < nearbyColliders.Length; i++)
        {
            FrozenCluster nearbyCluster = nearbyColliders[i].GetComponentInParent<FrozenCluster>();
            if (nearbyCluster && !nearbyClusters.Contains(nearbyCluster))
            {
                nearbyClusters.Add(nearbyCluster);
                continue;
            }

            PhysicalProperties nearbyPhysicalProperties = nearbyColliders[i].GetComponentInParent<PhysicalProperties>();
            if (!nearbyPhysicalProperties || nearbyPhysicalProperties == this || !nearbyPhysicalProperties.isFrozen)
            {
                continue;
            }

            nearbyCluster = nearbyPhysicalProperties.frozenCluster;
            if (nearbyCluster && !nearbyClusters.Contains(nearbyCluster))
            {
                nearbyClusters.Add(nearbyCluster);
            }
        }

        return nearbyClusters;
    }

    FrozenCluster CreateFrozenCluster()
    {
        GameObject clusterObject = new GameObject("FrozenCluster");
        clusterObject.transform.position = transform.position;
        return clusterObject.AddComponent<FrozenCluster>();
    }

    public void CopyStatsFrom(PhysicalProperties other)
    {
        if (!other)
        {
            return;
        }

        flashPoint = other.flashPoint;
        temperature = other.temperature;
        freezingPoint = other.freezingPoint;
        isIgnited = other.isIgnited;
        pressureGenerationRate = other.pressureGenerationRate;
        heatResistance = other.heatResistance;
        manaResistance = other.manaResistance;
        // manaCharge = other.manaCharge;
        manaCharge = 1;
        isFrozen = true;
    }

    public void ApplyMeanStatsWith(PhysicalProperties other)
    {
        if (!other)
        {
            return;
        }

        flashPoint = (flashPoint + other.flashPoint) / 2f;
        temperature = (temperature + other.temperature) / 2f;
        freezingPoint = (freezingPoint + other.freezingPoint) / 2f;
        isIgnited = isIgnited || other.isIgnited;
        pressureGenerationRate = (pressureGenerationRate + other.pressureGenerationRate) / 2f;
        heatResistance = (heatResistance + other.heatResistance) / 2f;
        manaResistance = (manaResistance + other.manaResistance) / 2f;
        // manaCharge = (manaCharge + other.manaCharge) / 2f;
        manaCharge = 1;
        isFrozen = true;
    }

    void StopGlowing()
    {
        isGlowing = false;
        material.SetColor("_Color", defaultColor);
    }

    void Glow()
    {
        isGlowing = true;
        material.SetColor("_Color", Color.yellow);
    }

    void Ignite()
    {
        isIgnited = true;
        material.SetColor("_Color", Color.red);
        StartCoroutine("Disintegrate");
        emberSmokeObject = Instantiate(emberSmokePrefab, transform.position, Quaternion.Euler(270,0,0));
        emberSmokeObject.transform.SetParent(transform);
        emberSmokeObject.transform.localScale = new Vector3(1,1,1);
    }

    IEnumerator Disintegrate()
    {
        float dissolveDuration = 5;
        float hitboxDissolveDuration = dissolveDuration - (dissolveDuration / 5);
        float dissolveStrength;
        float elapsedTime = 0;

        while ( elapsedTime < dissolveDuration )
        {
            elapsedTime += Time.deltaTime;

            dissolveStrength = Mathf.Lerp(-0.05f, 1f, elapsedTime / dissolveDuration);
            if (sphereCollider)
            {
                sphereCollider.radius = Mathf.Lerp(0.5f, 0.0f, elapsedTime / hitboxDissolveDuration);
                sphereCollider.center = new Vector3(0,Mathf.Lerp(0f, -0.5f, elapsedTime / hitboxDissolveDuration),0);
            }
            material.SetFloat("_DissolveStrength", dissolveStrength);

            yield return null;
        }

        emberSmokeObject.transform.SetParent(null);
        emberSmokeObject.transform.localScale = new Vector3(1,1,1);
        Destroy(gameObject);
    }

    [ContextMenu("AddOneMana")]
    void AddOneMana() // This method exists to test in the inspector
    {
        AddMana(1f);
    }

    public void AddMana(float manaAmount)
    {
        // [a.] Let's assume mana resistance is 0.5 and we're sending in 10 mana
        // [b.] Let's assime mana resistance is -0.5 and we're "sending in" 10 mana
        manaResistance = Mathf.Clamp(manaResistance, -1f, 1f);
        // [a.] 10 * 0.5 = 5 (heat = 5)
        // [b.] 10 * -0.5 = -5 (heat = -5)
        float manaConvertedToHeat = manaAmount * manaResistance;
        
        // [a.] 10 * 1 = 10 (so far mana = 10)
        // [b.] 10 * -1 = 10 (so far mana = -10)
        manaAmount = manaAmount * Mathf.Sign(manaResistance);
        // [a.] 10 - 5 = 5 (mana = 5)
        // [b.] -10 - -5 = -5 (mana = -5)
        manaAmount = manaAmount - manaConvertedToHeat;
        if (Mathf.Abs(manaAmount) < 0.01f) manaAmount = Mathf.Sign(manaAmount); // If the amount of mana being added or removed is really insanely tiny, just make it 1 instead xd
        manaCharge += manaAmount; 
        // Problem: I'm running into a problem here. When I try to cool down an object to 0 it repeatedly halves over and over and over again (assuming the manaResistance is -0.5). Is does this because in CastLogic.cs it does this if statement before calling this functions: if (flowableMana > physicalProperties.manaCharge) flowableMana = physicalProperties.manaCharge; // This function is to prevent the player from siphoning out more mana than the spell actually has. How do I solve this? I don't like that the siphoning process takes so long due to this halving.
        // Solution: I have decided to make that code not relevant for a spell's mana amount. Therefore, a spell's mana charge is theoretically able to be negative (although it's useless)
        temperature += manaConvertedToHeat;
    }

    // void OnTriggerEnter(Collider collision)
    // {
        
    // }

    void OnTriggerStay(Collider collision) // Call when touching something
    {
        if (collision.gameObject.tag == "Spark")
        {
            tempChangeDirection = (collision.transform.position - transform.position).normalized;
            temperature += 1;
        }

        if (collision.gameObject.tag == "PhysicalObject") // If touching physical object
        {
            PhysicalProperties collisionPhysicalProps = collision.gameObject.transform.GetComponent<PhysicalProperties>(); // Get reference
            if (Mathf.Abs(collisionPhysicalProps.temperature) >= Mathf.Abs(temperature)) // If the collided object's temperature is greater than THIS object's temperature...
            {
                tempChangeDirection = (collision.transform.position - transform.position).normalized;
                float temperatureTransferRate = (collisionPhysicalProps.temperature - temperature) / heatResistance; // Multiply difference in temps by conductivity
                temperature += 0.01f * temperatureTransferRate; // Add this much heat to THIS object
                collisionPhysicalProps.temperature -= 0.01f * temperatureTransferRate; // Delete this much heat from the collided object
            }
        }
    }
}
