using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PhysicalProperties : MonoBehaviour
{
    [SerializeField] float flashPoint; // Flash Point: Temperature required to ignite using external source
    public float temperature = 0;
    public bool isIgnited;
    public float pressureGenerationRate = 2f;
    Material material;
    Color defaultColor;
    SphereCollider sphereCollider;
    [SerializeField] float heatResistance; // Resistance to EXTERNAL HEAT sources
    public float manaResistance; // Resistance to mana flow
    // To adhere to the magic system, the higher the mana resistance, the more internal heat is generated by a mana current.
    public float manaCharge = 0;
    [SerializeField] GameObject emberSmokePrefab;
    GameObject emberSmokeObject;

    void Start()
    {
        material = GetComponent<Renderer>().material;
        defaultColor = material.GetColor("_Color");
        sphereCollider = GetComponent<SphereCollider>();
    }

    void Update()
    {
        if (isIgnited && temperature < flashPoint)
        {
            temperature = flashPoint;
        }
        if (temperature < 6)
        {
            StopGlowing();
        }
        if (temperature > 6 * flashPoint / 7 && temperature < flashPoint)
        {
            Glow();
        }
        if (temperature >= flashPoint && !isIgnited)
        {
            Ignite();
        }
    }

    void StopGlowing()
    {
        material.SetColor("_Color", defaultColor);
    }

    void Glow()
    {
        material.SetColor("_Color", Color.yellow);
    }

    void Ignite()
    {
        isIgnited = true;
        material.SetColor("_Color", Color.red);
        StartCoroutine("Disintegrate");
        emberSmokeObject = Instantiate(emberSmokePrefab, transform.position, Quaternion.Euler(270,0,0));
        emberSmokeObject.transform.SetParent(transform);
        emberSmokeObject.transform.localScale = new Vector3(1,1,1);
    }

    IEnumerator Disintegrate()
    {
        float dissolveDuration = 5;
        float hitboxDissolveDuration = dissolveDuration - (dissolveDuration / 5);
        float dissolveStrength;
        float elapsedTime = 0;

        while ( elapsedTime < dissolveDuration )
        {
            elapsedTime += Time.deltaTime;

            dissolveStrength = Mathf.Lerp(-0.05f, 1f, elapsedTime / dissolveDuration);
            if (sphereCollider)
            {
                sphereCollider.radius = Mathf.Lerp(0.5f, 0.0f, elapsedTime / hitboxDissolveDuration);
                sphereCollider.center = new Vector3(0,Mathf.Lerp(0f, -0.5f, elapsedTime / hitboxDissolveDuration),0);
            }
            material.SetFloat("_DissolveStrength", dissolveStrength);

            yield return null;
        }

        emberSmokeObject.transform.SetParent(null);
        emberSmokeObject.transform.localScale = new Vector3(1,1,1);
        Destroy(gameObject);
    }

    [ContextMenu("AddOneMana")]
    void AddOneMana() // This method exists to test in the inspector
    {
        AddMana(1f);
    }

    public void AddMana(float manaAmount)
    {
        manaResistance = Mathf.Clamp(manaResistance, -1f, 1f);
        float manaConvertedToHeat = manaAmount * manaResistance;
        
        manaCharge += manaAmount - manaConvertedToHeat;
        temperature += manaConvertedToHeat;
    }

    void OnTriggerEnter(Collider collision)
    {
        if (collision.gameObject.tag == "Spark")
        {
            temperature += 10;
        }
    }

    void OnTriggerStay(Collider collision) // Call when touching something
    {
        if (collision.gameObject.tag == "PhysicalObject") // If touching physical object
        {
            PhysicalProperties collisionPhysicalProps = collision.gameObject.transform.GetComponent<PhysicalProperties>(); // Get reference
            if (collisionPhysicalProps.temperature >= temperature) // If the collided object's temperature is greater than THIS object's temperature...
            {
                float temperatureTransferRate = Mathf.Abs(temperature - collisionPhysicalProps.temperature) / heatResistance; // Multiply difference in temps by conductivity
                temperature += 0.01f * temperatureTransferRate; // Add this much heat to THIS object
                collisionPhysicalProps.temperature -= 0.01f * temperatureTransferRate; // Delete this much heat from the collided object
            }
        }
    }
}
